name: Release Please

on:
  push:
    branches:
      - main

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.changes.outputs.modules }}
    steps:
      - uses: actions/checkout@v2
      - id: changes
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');
            const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
            const latestRelease = await github.repos.getLatestRelease({ owner, repo });
            execSync('git pull --tags');
            const diff = execSync(`git diff --name-only tags/${latestRelease.data.tag_name}`, { encoding: 'utf-8'});
            const modules = [...new Set([...diff.matchAll(/^modules\/(.+?)\//mg)].map(group => group[1]))]
            console.log(`::set-output name=modules::${JSON.stringify(Array.from(modules))}`);
  release-please:
    runs-on: ubuntu-latest
    needs: find-changes
    if: needs['find-changes'].outputs.modules != '[]'
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs['find-changes'].outputs.modules) }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          release-type: node
          monorepo-tags: true
          path: modules/${{ matrix.module }}
          token: ${{ secrets.GITHUB_TOKEN }}
          package-name: ${{ matrix.module }}
